# application-dev.yml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uberlike_app_database
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/uberlike_app_database
    username: postgres
    password: 
  flyway:
    enabled: true
    locations: classpath:db/migration
    user: uberuser
    password: uberuserpassword
    url: jdbc:postgresql://localhost:5432/uberlike_app_database
    baseline-on-migrate: true
    validate-on-migrate: true
  data:
    redis:
      host: localhost
      port: 6379
my-test-property: ThisIsATestFromDevProfile
mailgun:
  api:
    key: 
    domain: sandbox813f4bd01ba34c41811f4c0a5ede81f9.mailgun.org
    url: https://api.mailgun.net/v3
twilio:
  account-sid: 
  auth-token: 
  whatsapp:
    from-number: 
    content-sid: 
jwt:
  secret: # 256-bit (Base64)
  refreshSecret: # 256-bit (Base64)
  expiration: 3600000  # 1 hora en milisegundos
  refreshExpirationDays: 30
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.core.env: TRACE
    org.springframework.beans.factory: DEBUG
# Configuración de Google OAuth2
google:
  client:
    id: 